version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mika
      - MONGO_INITDB_DATABASE=thedb
      - MONGO_INITDB_ROOT_PASSWORD=mika
    volumes:
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "./volume:/data/db"
